# Numpy Lecture

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [10]:
#  creating arrays

import numpy as np
list1=[1,2,3,4,5]
arr1=np.array(list1)
arr1



arr1.shape


(5,)

In [11]:
list2=[[1,2,3],[8,6,7]]

arr2=np.array(list2)
arr2.shape

(2, 3)

In [19]:
list3=[
[[1,2,3,4],[8,6,7,7]],
[[13,22,13,78],[18,16,17,67]],
[[12,23,33,89],[88,60,70,45]]
    
]
arr3=np.array(list3)
arr3

array([[[ 1,  2,  3,  4],
        [ 8,  6,  7,  7]],

       [[13, 22, 13, 78],
        [18, 16, 17, 67]],

       [[12, 23, 33, 89],
        [88, 60, 70, 45]]])

In [21]:
arr3.shape

(3, 2, 4)

In [25]:
arr4=np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
arr4=np.full((2,3),8)
arr4

array([[8, 8, 8],
       [8, 8, 8]])

In [32]:
arr4=np.arange(2,10)
arr4

array([2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr5=np.linspace(0,1,5)
arr5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])